version: '3.1'

services:
  node14:
    container_name: node14
    image: wachira90/node:14.15.1
    volumes:
       - app14:/usr/src/app/
    ports:
      - "8014:8000"

  node16:
    container_name: node16
    image: wachira90/node:16.13.2
    volumes:
       - app16:/usr/src/app/
    ports:
      - "8016:8000"

volumes:
  app16:
  app14:

networks:
  default:
